### ISSUE TITLE
Python 3.7 breaks this program

### ISSUE THREAD

**Issue by shinn16** [alendit/sphinx-pyreverse#11]
Here is the reported error:
~~~~
  File "/home/patrick/Gitlab/venv/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/patrick/Gitlab/venv/lib/python3.7/site-packages/sphinx_pyreverse/__init__.py", line 14
    except ImportError, error:
~~~~
Upon examining the source files, the issue appears to be the syntax used to import ImportError. On line 14 of __init__.py, the syntax used to import the module is not supported in Python 3.7. Here is the full stack trace if it helps.

~~~~
Running Sphinx v1.8.4

Exception occurred:
  File "/home/patrick/Gitlab/venv/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/patrick/Gitlab/venv/lib/python3.7/site-packages/sphinx_pyreverse/__init__.py", line 14
    except ImportError, error:
                      ^
SyntaxError: invalid syntax
The full traceback has been saved in /tmp/sphinx-err-7cbym_nd.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:19: html] Error 2
(venv) [patrick@Laptop sphinx]$ cat /tmp/sphinx-err-7cbym_nd.log 
# Sphinx version: 1.8.4
# Python version: 3.7.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/patrick/Gitlab/venv/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/patrick/Gitlab/venv/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/patrick/Gitlab/venv/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/patrick/Gitlab/venv/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/patrick/Gitlab/venv/lib/python3.7/site-packages/sphinx_pyreverse/__init__.py", line 14
    except ImportError, error:
                      ^
SyntaxError: invalid syntax
(venv) [patrick@Laptop sphinx]$ 
~~~~

**Comment by arthurlogilab** [comment]
Same here...

**Comment by doublethefish** [comment]
Closing as fixed. We now test against rolling python3 and python2 (for now). The python version last tested by the CI was 3.7.4.
